language: cpp
os: osx

addons:
    homebrew:
        packages:
            - qt5

script:
    # XXX: please chmod +x the shell script.
    - bash ./scripts/macos_build.sh
    - bash ./scripts/macos_post_build.sh
