language: cpp
os: osx

before_install:
    - brew update
    - brew install qt5

script:
    # XXX: please chmod +x the shell script.
    - sh ./scripts/macos_build.sh
    - ./scripts/macos_post_build.sh
